# @URL=https://g9hpa0pahg.execute-api.us-east-1.amazonaws.com/prod
@URL=https://api.translateappdemo.site
POST {{URL}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "sourceLang": "en",
    "targetLang": "hy",
    "sourceText": "walk"
}

###
GET {{URL}} HTTP/1.1
Content-Type: application/json
Accept: application/json
